apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8080
        env:
          - name: TARGET
            value: "APP-1"