apiVersion: v1
kind: Service
metadata:
  name: sd-example
  namespace: test
  labels:
    app: sd-example
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 3333
  selector:
    app: sd-example

